[module/date]
type = internal/date
interval = 5

date = "%d.%m.%Y"
;date-alt = " %d.%m.%Y"

time = %H:%M
;time-alt = %H:%M

;format-prefix = 
format-prefix-foreground = ${colors.info}
format-underline = ${colors.info}
;format-underline = ${colors.info}

label = "%date% %time%"
