[module/i3]
type = internal/i3
;format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
strip-wsnumbers = true

; pacman -S ttf-font-awesome
; https://fontawesome.com/cheatsheet?from=io
;ws-icon-0 = "1;"
;ws-icon-1 = "2;"
;ws-icon-2 = "3;"
;ws-icon-3 = "4;"
;ws-icon-4 = "5;"
;ws-icon-5 = "9;"
;ws-icon-6 = "10;"
;ws-icon-default = 

; Only show workspaces on the same output as the bar
pin-workspaces = true

label-mode-padding = 2
label-mode-foreground = #000
label-mode-background = ${colors.info}

; focused = Active workspace on focused monitor
label-focused = %name% %icon%
label-focused-background = ${module/bspwm.label-focused-background}
label-focused-underline = ${module/bspwm.label-focused-underline}
label-focused-padding = ${module/bspwm.label-focused-padding}

; unfocused = Inactive workspace on any monitor
label-unfocused = %name% %icon%
label-unfocused-padding = ${module/bspwm.label-occupied-padding}

; visible = Active workspace on unfocused monitor
label-visible = %name% %icon%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %name% %icon%
label-urgent-foreground = ${module/bspwm.label-urgent-foreground}
label-urgent-background = ${module/bspwm.label-urgent-background}
label-urgent-padding = ${module/bspwm.label-urgent-padding}
