[module/volume]
type = internal/volume

format-volume = <ramp-volume>
format-volume-foreground = ${colors.info}

;format-muted-prefix = "  "
format-muted-foreground = ${colors.foreground-alt}
label-muted =

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
